workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/PetraTatoo.xcworkspace"
        XCODE_SCHEME: "PetraTatoo"
        XCODE_PROJECT: "ios/PetraTatoo.xcodeproj"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app (unsigned for device)
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            clean build
      - name: Package IPA
        script: |
          mkdir -p Payload
          APP_PATH=$(find $HOME/Library/Developer/Xcode/DerivedData -name "*.app" | head -n 1)
          cp -r "$APP_PATH" Payload/
          zip -r PetraTatoo.ipa Payload
    artifacts:
      - *.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - m.daya.nutrino@gmail.com
        notify:
          success: true
          failure: true
