workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      vars:
        PACKAGE_NAME: "com.myapp"
      node: 18.17.0
      java: 17
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - m.daya.nutrino@gmail.com
        notify:
          success: true
          failure: true

  react-native-ios:
    name: React Native iOS (Manual Code Signing Required)
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - manual
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.myapp
      vars:
        XCODE_WORKSPACE: "ios/PetraTatto.xcworkspace"
        XCODE_SCHEME: "PetraTatto"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Set up provisioning profiles settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - m.daya.nutrino@gmail.com
        notify:
          success: true
          failure: true
